# Generated by Django 3.2.7 on 2021-10-14 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_variations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Variations',
            new_name='Variation',
        ),
    ]
