# Generated by Django 3.2.7 on 2021-11-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20211101_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='mrp_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
