# Generated by Django 3.2.7 on 2021-11-09 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_product_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(default='default_product.png', upload_to='photos/products'),
        ),
    ]
