# Generated by Django 3.2.7 on 2021-11-06 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_wishcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='wishcart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carts.cart'),
        ),
    ]
