# Generated by Django 3.2.7 on 2021-10-23 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
