# Generated by Django 3.2.7 on 2021-11-09 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(default='no_image.png', upload_to='photos/categories'),
        ),
    ]
