# Generated by Django 3.2.7 on 2021-10-28 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderproduct_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Accepted', 'Accepted'), ('Order Shipped', 'Order Shipped'), ('Order Out for Delivery', 'Order Out for Delivery'), ('Order Delivered', 'Order Delivered'), ('Return', 'Return'), ('Return collected', 'Return collected'), ('Cancelled', 'Cancelled')], default='New', max_length=30),
        ),
    ]
